AWSTemplateFormatVersion: 2010-09-09
Description: fn-bot
Transform:
- AWS::Serverless-2016-10-31
Resources:
  speakToCouncilFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/speakToCouncil/speak-to-council.speakToCouncil
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonDynamoDBReadOnlyAccess
      CodeUri: s3://fn-bot-sam-package/dd59bc663f2767fce663b7d11eff9b9e
  fnBotServicesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ServiceName
        Type: String
  bulkServiceUpload:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/bulkServiceUpload/bulk-upload.bulkUpload
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      - AmazonDynamoDBFullAccess
      - AmzaonS3ReadOnlyAccess
      CodeUri: s3://fn-bot-sam-package/dd59bc663f2767fce663b7d11eff9b9e
