version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fnvoicebotone"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fcvajeue9xxx"
s3_prefix = "fnvoicebotone"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Workload=\"dev\""

